commit-5

diff --git a/jenkinsfiles/frontend b/jenkinsfiles/frontend
--- a/jenkinsfiles/frontend
+++ b/jenkinsfiles/frontend
@@ -156,9 +156,17 @@ pipeline {
                             BUILD_NUMBER=${BUILD_NUMBER}
                             echo $BUILD_NUMBER
 
+                            # Validate file existence
+                            if [ ! -f "${YAML_FILE}" ]; then
+                                echo "ERROR: ${YAML_FILE} not found!"
+                                ls -la
+                                exit 1
+                            fi
+
                             # push this image to your git hub
-                            sed -i "s#image:.*#image: ${REPOSITORY_URI}/${AWS_ECR_REPO_NAME}:$BUILD_NUMBER#g" ${YAML_FILE}
-                            git add .
+                            sed -i "/name: react-frontend/{n;s#image: .*#image: ${REPOSITORY_URI}/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}#}" ${YAML_FILE}
+
+                            git add ${YAML_FILE}
                             git commit -m "Update ${AWS_ECR_REPO_NAME} Image to version \${BUILD_NUMBER}"
                             git push https://${git_token}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
         
